== Exceptions
Another well known feature of C++ is exceptions. YAOOC has this feature as well. The syntax is:

[source,c]
-------------------
TRY {
  ...
} CATCH (exception_type,exception_var) {
  ...
} ETRY
-------------------
Where exception_type is the type of exception and exception_var is the variable to which the exception is assigned.
Note the comma between exception type and exception var.

.Exception Rules
* All exceptions must be a descendant of yaooc_exeception (shown below).
* There can be multiple CATCH blocks.
* TRY/CATCH blocks can be nested -- either in TRY portion or CATCH portion.
* CATCH will catch exception of the type specified and types that are derived from exception_type.
* An exception stack is created for each thread.

To throw an exception, use the THROW macro.

[source,c]
THROW(new(exception_type))

If any thread throws an exception that is not caught, then a message indicating uncaught exception is printed to stderr and the program is terminated.

All exceptions should be a descendant of yaooc_exception.
The class definition of yaooc_exception is:

[source,c]
-------------------
%class yaooc_exception : yaooc_object
{
    yaooc_exception() : what_(NULL) { }

    yaooc_exception_ctor_v(int error_code,const char*fmt,... args)
    {
      this->error_code_=error_code;
      va_list args2;
      va_copy(args2,args);
      int size_needed=vsnprintf(NULL,0,fmt,args2);
      va_end(args2);
      if(size_needed > 0) {
        this->what_=MALLOC(++size_needed);
        vsnprintf(this->what_,size_needed,fmt,args);
      }
    }

    ~yaooc_exception()
    {
      if(this->what_)
        FREE(this->what_);
    }

    yaooc_exception(src) : yaooc_exception()
    {
      yaooc_exception_assign(this,src);
    }

    operator=(src)
    {
      yaooc_exception_dtor(this);
      this->error_code_=src->error_code_;
      this->what_ = src->what_ ? STRDUP(src->what_) : NULL;
    }

  table:
    const char* what() const { return this->what_; }
    int error_code() const { return this->error_code_; }

  instance:
    char* what_;
    int error_code_;
};
-------------------
The constructor yaooc_exception_ctor_v creates an exception using printf syntax.
For example,

[source,c]
THROW(new_ctor(yaooc_exception,yaooc_exception_ctor_v,"Error in file %s at line %d",__FILE__,__LINE__));

=== TRY/CATCH blocks have a garbage bag
Objects that were created within the scope of the TRY/CATCH block need to be deleted -- even if an exception is thrown.
YAOOC facilitates this by providing a garbage bag in the TRY/CATCH block.
The following macros can be used within a TRY/CATCH block.

.Exception Garbage Bag Macros
[options="header"]
|====================================
|Macro|Purpose
|egb_save(ptr)|Save pointer in exception garbage bag and returns value being saved
|egb_clear|Removes pointers from exception garbage bag without deleting pointers
|egb_delete|Deletes pointers in exception garbage bag. More pointer can still be saved
|====================================
Usually, only the egb_save macro is used.

The TRY/CATCH block garbage bag is created when the TRY keyword is encountered. A unique garbage bag is created for each TRY encountered. Pointers saved (egb_save) in garbage bag will be saved in the current TRY/CATCH block garbage bag. The garbage bag is deleted (and all pointers contained) when the TRY/CATCH block goes out of scope. If a method is called within the TRY/CATCH block, that method can use egb_save to save pointers in the garbage bag.

[source,c]
-------------------
TRY {  /* Garbage bag 1 is created here */
  ... /* egb_save saves to garbage bag 1 */
  TRY { /* Garbage bag 2 is created here */
    ...   /* egb_save saves to garbage bag 2 */
  } CATCH(exception,e) {
    ...
  } ETRY /* Garbage bag 2 is deleted here */
} CATCH(exception,e) {
   ...
} ETRY /* Garbage bag 1 is deleted here */
-------------------
